"""
Discord Quiz Bot 실행 및 테스트 가이드
"""

print("🤖 Discord Quiz Bot - 업데이트 완료!")
print("=" * 50)
print()
print("📋 변경사항:")
print("1. ✅ 구분자 변경: ';' → '★'")
print("2. ✅ 3시간 간격 문제/답변 전송")
print()
print("🚀 실행 방법:")
print("1. 환경변수 설정 확인: python check_env.py")
print("2. 퀴즈 생성기 실행: python gemini_query_bot.py")
print("3. Discord 봇 실행: python discord_bot.py")
print("   또는 통합 실행: python main_replit.py")
print()
print("🧪 테스트 방법:")
print("1. 구분자 테스트: python test_separator.py")
print("2. 30초 간격 테스트: python discord_bot_test.py")
print("3. 답변 타이밍 테스트: python test_answer_timing.py")
print()
print("💡 Discord 명령어:")
print("- /퀴즈: 수동으로 퀴즈 요청")
print("- /답: 최신 퀴즈 답변 확인")
print("- /답 [ID]: 특정 퀴즈 답변 확인")
print()
print("⏰ 자동 실행 주기:")
print("- 퀴즈 생성: 1시간마다")
print("- 문제 전송: 3시간마다 (새 퀴즈 있을 때)")
print("- 답변 전송: 문제 전송 후 30분")
print()
print("=" * 50)
